spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/booknest_db
spring.datasource.username=giadarusso
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.jpa.open-in-view=false
